struct RenderSettingsUniform {
    sun_direction: vec4<f32>,
    sky_color: vec4<f32>,
    material_colors: array<vec4<f32>, 1024>,

    ambient_light: f32,
    sun_contribution: f32,
    chunk_lod_scale: f32,
    node_lod_scale: f32,

    ray_epsilon: f32,
    max_chunk_steps: f32,
    max_node_steps: f32,
    vegetation_density: f32,
    vegetation_length: f32,
    vegetation_scale: f32,
    vegetation_max_distance: f32,
    vegetation_far_step_scale: f32,
    vegetation_far_reduce_start: f32,
    vegetation_near_search_radius: f32,
    vegetation_far_search_radius: f32,
    vegetation_shadow_distance: f32,
    vegetation_animation_distance: f32,
    water_reflection_distance: f32,
    water_shadow_distance: f32,
    ao_intensity: f32,
    hybrid_near_radius: f32,
    hybrid_debug_tint: f32,
    _hybrid_pad0: f32,
    _hybrid_pad1: f32,
};
