[workspace]
members = ["client", "server", "protocol"]
default-members = ["client"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"

[workspace.dependencies]
capy-protocol = { path = "protocol" }
engine = { package = "capy-engine-client", path = "../engine/client" }
capy-engine-server = { path = "../engine/server" }
capy-engine-protocol = { path = "../engine/protocol" }
capy-server = { path = "server" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
