[package]
name = "capy_assets"
version.workspace = true
edition.workspace = true

[dependencies]
capy_core = { path = "../core" }

thiserror.workspace = true
bytemuck.workspace = true
lz4_flex.workspace = true
xxhash-rust.workspace = true
bevy_ecs.workspace = true
glam.workspace = true
fbxcel-dom.workspace = true
image.workspace = true

[lints]
workspace = true
