[workspace]
members = ["crates/engine", "crates/game", "crates/style"]
default-members = ["crates/game"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
proc-macro2 = { version = "1", features = ["span-locations"] }
syn = { version = "2", features = ["full", "visit"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
pollster = "1"
taffy = { version = "0.14", default-features = false, features = ["std", "taffy_tree", "flexbox"] }
raw-window-handle = "0.6"
wgpu = "30.0.1"
winit = "0.30.13"
engine = { path = "crates/engine" }
glam = "0.33"
bytemuck = { version = "1", features = ["derive"] }
fontdue = "0.9"
