[package]
name = "capy_render"
version.workspace = true
edition.workspace = true

[dependencies]
capy_core = { path = "../core" }

wgpu.workspace = true
pollster.workspace = true
bevy_ecs.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
glam.workspace = true
tracing.workspace = true

[lints]
workspace = true
