[package]
name = "capy_render"
version.workspace = true
edition.workspace = true
build = "build.rs"

[features]
dlss = ["dep:uuid", "dep:bitflags", "dep:bindgen", "dep:cc"]

[dependencies]
capy_core = { path = "../core" }

wgpu.workspace = true
pollster.workspace = true
bevy_ecs.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
glam.workspace = true
tracing.workspace = true
uuid = { workspace = true, optional = true }
ash = "0.38"
bitflags = { version = "2", optional = true }
fsr = { version = "0.1", features = ["vulkan"] }
fsr-sys = "0.1"

[build-dependencies]
bindgen = { version = "0.72", optional = true }
cc = { version = "1", optional = true }

[lints]
workspace = true
