[package]
name = "capy_render"
version.workspace = true
edition.workspace = true
build = "build.rs"

[features]
dlss = [
    "dep:uuid",
    "dep:bitflags",
    "dep:windows",
    "dep:bindgen",
    "dep:cc",
]
fsr = ["dep:windows", "dep:windows-core", "dep:bindgen", "dep:cc", "wgpu/static-dxc"]

[dependencies]
capy_core = { path = "../core" }

wgpu.workspace = true
pollster.workspace = true
bevy_ecs.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
glam.workspace = true
tracing.workspace = true
uuid = { workspace = true, optional = true }
ash = "0.38"
bitflags = { version = "2", optional = true }
windows = { version = "0.62", optional = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
] }
windows-core = { version = "0.62", optional = true }

[build-dependencies]
bindgen = { version = "0.72", optional = true }
cc = { version = "1", optional = true }

[lints]
workspace = true
