//! Raw FFI bindings generated by bindgen from the FidelityFX SDK headers,
//! plus thin safe wrappers around the core API functions and manually-defined
//! DX12 backend types (blocklisted by bindgen due to ID3D12Device dependency).

// Bindings inner module — suppresses naming/style lints from generated code.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::upper_case_acronyms
)]
mod inner {
    include!(concat!(env!("OUT_DIR"), "/fsr_bindings.rs"));
}
pub(crate) use inner::*;

use super::FsrError;

// ---------------------------------------------------------------------------
// Constants from C preprocessor macros — bindgen cannot emit #define macros,
// so we compute and define them manually.
//
// FFX_API_MAKE_EFFECT_SUB_ID(effectId, sub) =
//     (effectId & 0x00ff_0000) | (sub & !0x00ff_0000)
// ---------------------------------------------------------------------------

// Upscaler (FFX_API_EFFECT_ID_UPSCALE = 0x0001_0000)
pub(crate) const FFX_API_CREATE_CONTEXT_DESC_TYPE_UPSCALE: u64 = 0x0001_0000;
pub(crate) const FFX_API_DISPATCH_DESC_TYPE_UPSCALE: u64 = 0x0001_0001;
pub(crate) const FFX_API_QUERY_DESC_TYPE_UPSCALE_GETJITTERPHASECOUNT: u64 = 0x0001_0004;
pub(crate) const FFX_API_QUERY_DESC_TYPE_UPSCALE_GETJITTEROFFSET: u64 = 0x0001_0005;

// Frame Generation (FFX_API_EFFECT_ID_FRAMEGENERATION = 0x0002_0000)
pub(crate) const FFX_API_CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATION: u64 = 0x0002_0001;
pub(crate) const FFX_API_CONFIGURE_DESC_TYPE_FRAMEGENERATION: u64 = 0x0002_0002;
pub(crate) const FFX_API_DISPATCH_DESC_TYPE_FRAMEGENERATION: u64 = 0x0002_0003;
pub(crate) const FFX_API_DISPATCH_DESC_TYPE_FRAMEGENERATION_PREPARE_V2: u64 = 0x0002_000c;
pub(crate) const FFX_API_CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATION_VERSION: u64 = 0x0002_000e;

/// FSR 3 Frame Generation version: 4.0.0 — `(4 << 22) | (0 << 12) | 0`.
pub(crate) const FFX_FRAMEGENERATION_VERSION: u32 = 4 << 22;

/// No swapchain proxy — we handle present/double-present ourselves.
pub(crate) const FFX_FRAMEGENERATION_FLAG_NO_SWAPCHAIN_CONTEXT_NOTIFY: u32 = 1 << 3;

/// Surface format constant for RGBA8 Unorm (matches `FfxApiSurfaceFormat` enum).
pub(crate) const FFX_API_SURFACE_FORMAT_R8G8B8A8_UNORM: u32 = 10;

// ---------------------------------------------------------------------------
// DX12 backend descriptor — manually defined because bindgen cannot resolve
// the `ID3D12Device*` field and skips the struct entirely.
// ---------------------------------------------------------------------------

/// `FFX_API_CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12` = 0x02
/// Computed from: `FFX_API_MAKE_BACKEND_SUB_ID(FFX_API_BACKEND_ID_DX12, 0x02)`
/// where `FFX_API_BACKEND_ID_DX12 = 0x00000000`.
pub(crate) const FFX_API_CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12: u32 = 0x02;

/// Mirrors `ffxCreateBackendDX12Desc` from `ffx_api_dx12.h`.
/// Layout: header (16 bytes) + device pointer (8 bytes) = 24 bytes.
#[repr(C)]
pub(crate) struct ffxCreateBackendDX12Desc {
    pub header: ffxCreateContextDescHeader,
    /// Pointer to `ID3D12Device` (passed as `*mut c_void`).
    pub device: *mut core::ffi::c_void,
}

// ---------------------------------------------------------------------------
// Safe wrappers
// ---------------------------------------------------------------------------

/// Create a FidelityFX context.
///
/// # Safety
/// `desc` must point to a valid, fully-initialised descriptor chain whose
/// lifetime exceeds the call.
pub(crate) unsafe fn create_context(
    context: *mut ffxContext,
    desc: *mut ffxCreateContextDescHeader,
) -> Result<(), FsrError> {
    FsrError::from_ffx(unsafe { ffxCreateContext(context, desc, core::ptr::null()) })
}

/// Destroy a FidelityFX context.
///
/// # Safety
/// `context` must have been successfully created with [`create_context`] and
/// must not be used after this call.
pub(crate) unsafe fn destroy_context(context: *mut ffxContext) -> Result<(), FsrError> {
    FsrError::from_ffx(unsafe { ffxDestroyContext(context, core::ptr::null()) })
}

/// Dispatch GPU work for a given context.
///
/// # Safety
/// `desc` must point to a valid dispatch descriptor matching the context type.
pub(crate) unsafe fn dispatch(
    context: *mut ffxContext,
    desc: *const ffxDispatchDescHeader,
) -> Result<(), FsrError> {
    FsrError::from_ffx(unsafe { ffxDispatch(context, desc) })
}

/// Configure a FidelityFX context (e.g. enable/disable frame generation).
///
/// # Safety
/// `desc` must point to a valid configure descriptor matching the context type.
pub(crate) unsafe fn configure(
    context: *mut ffxContext,
    desc: *const ffxConfigureDescHeader,
) -> Result<(), FsrError> {
    FsrError::from_ffx(unsafe { ffxConfigure(context, desc) })
}

/// Query information from a context (e.g. jitter phase count / offset).
///
/// # Safety
/// `desc` must point to a valid query descriptor.
pub(crate) unsafe fn query(
    context: *mut ffxContext,
    desc: *mut ffxQueryDescHeader,
) -> Result<(), FsrError> {
    FsrError::from_ffx(unsafe { ffxQuery(context, desc) })
}
