[package]
name = "capy_world_editor"
version.workspace = true
edition.workspace = true

[dependencies]
capy_core = { path = "../core" }
capy_engine = { path = "../engine" }
capy_world = { path = "../world" }
capy_assets = { path = "../assets" }
capy_shared = { path = "../shared" }
capy_input = { path = "../input" }
capy_render = { path = "../render" }
capy_ui = { path = "../ui" }

anyhow.workspace = true
bevy_ecs.workspace = true
glam.workspace = true
egui.workspace = true
wgpu.workspace = true
winit.workspace = true

[lints]
workspace = true
