[package]
name = "capy_shared"
version.workspace = true
edition.workspace = true

[features]
dlss = ["capy_render/dlss"]

[dependencies]
capy_core = { path = "../core" }
capy_engine = { path = "../engine" }
capy_render = { path = "../render" }
capy_ui = { path = "../ui" }
capy_window = { path = "../window" }

bevy_ecs.workspace = true
egui.workspace = true
wgpu.workspace = true

[lints]
workspace = true
