[package]
name = "capy_game"
version.workspace = true
edition.workspace = true

[dependencies]
capy_engine = { path = "../engine" }
capy_input = { path = "../input" }
capy_render = { path = "../render" }
capy_core = { path = "../core" }
capy_assets = { path = "../assets" }
capy_shared = { path = "../shared" }

anyhow.workspace = true
bevy_ecs.workspace = true
glam.workspace = true

[lints]
workspace = true
