[package]
name = "capy_game"
version.workspace = true
edition.workspace = true

[features]
dlss = ["capy_render/dlss", "capy_shared/dlss"]
fsr = ["capy_render/fsr", "capy_shared/fsr"]

[dependencies]
capy_engine = { path = "../engine" }
capy_input = { path = "../input" }
capy_render = { path = "../render" }
capy_window = { path = "../window" }
capy_core = { path = "../core" }
capy_assets = { path = "../assets" }
capy_world = { path = "../world" }
capy_shared = { path = "../shared" }

anyhow.workspace = true
bevy_ecs.workspace = true
glam.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
